### ISSUE TITLE
Untrack unwanted files

### ISSUE THREAD

**Issue by AlexIliescu11** [Essential-Structures/ItSchool-cursJava#1]
Please consider to untrack `.idea` package.

You can use the following commands:
`git rm --cached <file>` This command removes the specified file from Git's tracking, but it keeps the file in your working directory.
`git rm -r --cached <directory>` This recursively removes all files within the specified directory from Git's tracking, while leaving them in your working directory.

![image](https://github.com/Essential-Structures/ItSchool-cursJava/assets/120710343/38f427be-68fa-4d51-a3ab-aa7f74fd926a)

**Comment by Essential-Structures** [comment]
So mi-a iesit sa scap de diretorul.idea din consola de git.
Nu inteleg de unde mi-a aparut acel out. I-am dat git rm -r out (am uitat sa scriu --cached, pt ca nu inteleg ce unde pe cine cum cach-uie), l-a sters local, dar vad ca inca apare tele.

**Comment by Essential-Structures** [comment]
Ok, uitasem sa dau commit. Merge.
