### ISSUE TITLE
Untrack unwanted files

### ISSUE THREAD

**Issue by AlexandruIliescu** [Essential-Structures/ItSchool-cursJava#4]
Please consider to remove unwanted files from github, like the ones with *.iml extension.

<img width="600" alt="image" src="https://github.com/user-attachments/assets/a62e5d38-4cfa-41fc-b124-cafd436fd328">

**Comment by Essential-Structures** [comment]
Correction done, thank you.

**Comment by AlexandruIliescu** [comment]
Great job!
